# -*- coding: utf-8 -*-

"""
Chemical information resource

class:
  - aa: amino-acid
  - dna: DNA
"""

GREEK_ALPHABET = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa',
                  'lambda', 'mu', 'nu', 'xi', 'omicron', 'pi', 'rho', 'sigma', 'tau', 'upsilon', 'phi',
                  'chi', 'psi', 'omega']

STRUCTURE_DATA_INFO = [
    {'name': 'ALA', 'type': 'residue', 'class': 'aa', 'mw': 89.00},
    {'name': 'ARG', 'type': 'residue', 'class': 'aa', 'mw': 174.20},
    {'name': 'ASN', 'type': 'residue', 'class': 'aa', 'mw': 132.12},
    {'name': 'ASP', 'type': 'residue', 'class': 'aa', 'mw': 133.10},
    {'name': 'ASX', 'type': 'residue', 'class': 'aa', 'mw': 132.61},
    {'name': 'CYS', 'type': 'residue', 'class': 'aa', 'mw': 121.15},
    {'name': 'GLN', 'type': 'residue', 'class': 'aa', 'mw': 146.15},
    {'name': 'GLU', 'type': 'residue', 'class': 'aa', 'mw': 147.13},
    {'name': 'GLX', 'type': 'residue', 'class': 'aa', 'mw': 146.64},
    {'name': 'GLY', 'type': 'residue', 'class': 'aa', 'mw': 75.07},
    {'name': 'HIS', 'type': 'residue', 'class': 'aa', 'mw': 155.16},
    {'name': 'ILE', 'type': 'residue', 'class': 'aa', 'mw': 131.17},
    {'name': 'LEU', 'type': 'residue', 'class': 'aa', 'mw': 131.17},
    {'name': 'LYS', 'type': 'residue', 'class': 'aa', 'mw': 146.19},
    {'name': 'MET', 'type': 'residue', 'class': 'aa', 'mw': 149.21},
    {'name': 'PHE', 'type': 'residue', 'class': 'aa', 'mw': 165.19},
    {'name': 'PRO', 'type': 'residue', 'class': 'aa', 'mw': 115.13},
    {'name': 'SER', 'type': 'residue', 'class': 'aa', 'mw': 105.09},
    {'name': 'THR', 'type': 'residue', 'class': 'aa', 'mw': 119.12},
    {'name': 'TRP', 'type': 'residue', 'class': 'aa', 'mw': 204.23},
    {'name': 'TYR', 'type': 'residue', 'class': 'aa', 'mw': 181.19},
    {'name': 'VAL', 'type': 'residue', 'class': 'aa', 'mw': 117.15},
    {'name': 'IVA', 'type': 'residue', 'class': 'aa', 'mw': 85.12},
    {'name': 'STA', 'type': 'residue', 'class': 'aa', 'mw': 157.15},
    {'name': 'ACE', 'type': 'residue', 'class': 'aa', 'mw': 43.30},
    {'name': 'H2O', 'type': 'residue', 'class': 'solvent', 'mw': 18.0},
    {'name': 'H', 'type': 'atom', 'class': 'element', 'mw': 1.00794},
    {'name': 'D', 'type': 'atom', 'class': 'element', 'mw': 2.01410178},
    {'name': 'HE', 'type': 'atom', 'class': 'element', 'mw': 4.00},
    {'name': 'LI', 'type': 'atom', 'class': 'element', 'mw': 6.941},
    {'name': 'BE', 'type': 'atom', 'class': 'element', 'mw': 9.01},
    {'name': 'B', 'type': 'atom', 'class': 'element', 'mw': 10.811},
    {'name': 'C', 'type': 'atom', 'class': 'element', 'mw': 12.0107},
    {'name': 'N', 'type': 'atom', 'class': 'element', 'mw': 14.0067},
    {'name': 'O', 'type': 'atom', 'class': 'element', 'mw': 15.9994},
    {'name': 'F', 'type': 'atom', 'class': 'element', 'mw': 18.998403},
    {'name': 'NE', 'type': 'atom', 'class': 'element', 'mw': 20.18},
    {'name': 'NA', 'type': 'atom', 'class': 'element', 'mw': 22.989769},
    {'name': 'MG', 'type': 'atom', 'class': 'element', 'mw': 24.305},
    {'name': 'AL', 'type': 'atom', 'class': 'element', 'mw': 26.98},
    {'name': 'SI', 'type': 'atom', 'class': 'element', 'mw': 28.09},
    {'name': 'P', 'type': 'atom', 'class': 'element', 'mw': 30.973762},
    {'name': 'S', 'type': 'atom', 'class': 'element', 'mw': 32.065},
    {'name': 'CL', 'type': 'atom', 'class': 'element', 'mw': 35.453},
    {'name': 'AR', 'type': 'atom', 'class': 'element', 'mw': 39.95},
    {'name': 'K', 'type': 'atom', 'class': 'element', 'mw': 39.0983},
    {'name': 'CA', 'type': 'atom', 'class': 'element', 'mw': 40.078},
    {'name': 'SC', 'type': 'atom', 'class': 'element', 'mw': 44.96},
    {'name': 'TI', 'type': 'atom', 'class': 'element', 'mw': 47.87},
    {'name': 'V', 'type': 'atom', 'class': 'element', 'mw': 50.94},
    {'name': 'CR', 'type': 'atom', 'class': 'element', 'mw': 51.9961},
    {'name': 'MN', 'type': 'atom', 'class': 'element', 'mw': 54.938045},
    {'name': 'FE', 'type': 'atom', 'class': 'element', 'mw': 55.845},
    {'name': 'CO', 'type': 'atom', 'class': 'element', 'mw': 58.93},
    {'name': 'NI', 'type': 'atom', 'class': 'element', 'mw': 58.6934},
    {'name': 'CU', 'type': 'atom', 'class': 'element', 'mw': 63.546},
    {'name': 'ZN', 'type': 'atom', 'class': 'element', 'mw': 65.409},
    {'name': 'GA', 'type': 'atom', 'class': 'element', 'mw': 69.72},
    {'name': 'GE', 'type': 'atom', 'class': 'element', 'mw': 72.64},
    {'name': 'AS', 'type': 'atom', 'class': 'element', 'mw': 74.9216},
    {'name': 'SE', 'type': 'atom', 'class': 'element', 'mw': 78.96},
    {'name': 'BR', 'type': 'atom', 'class': 'element', 'mw': 79.90},
    {'name': 'KR', 'type': 'atom', 'class': 'element', 'mw': 83.80},
    {'name': 'RB', 'type': 'atom', 'class': 'element', 'mw': 85.47},
    {'name': 'SR', 'type': 'atom', 'class': 'element', 'mw': 87.62},
    {'name': 'Y', 'type': 'atom', 'class': 'element', 'mw': 88.91},
    {'name': 'ZR', 'type': 'atom', 'class': 'element', 'mw': 91.22},
    {'name': 'NB', 'type': 'atom', 'class': 'element', 'mw': 92.91},
    {'name': 'W', 'type': 'atom', 'class': 'element', 'mw': 95.94},
    {'name': 'MO', 'type': 'atom', 'class': 'element', 'mw': 95.94},
    {'name': 'TC', 'type': 'atom', 'class': 'element', 'mw': 98.0},
    {'name': 'RU', 'type': 'atom', 'class': 'element', 'mw': 101.07},
    {'name': 'RH', 'type': 'atom', 'class': 'element', 'mw': 102.91},
    {'name': 'PD', 'type': 'atom', 'class': 'element', 'mw': 106.42},
    {'name': 'AG', 'type': 'atom', 'class': 'element', 'mw': 107.8682},
    {'name': 'CD', 'type': 'atom', 'class': 'element', 'mw': 112.411},
    {'name': 'IN', 'type': 'atom', 'class': 'element', 'mw': 114.82},
    {'name': 'SN', 'type': 'atom', 'class': 'element', 'mw': 118.71},
    {'name': 'SB', 'type': 'atom', 'class': 'element', 'mw': 121.76},
    {'name': 'TE', 'type': 'atom', 'class': 'element', 'mw': 127.60},
    {'name': 'I', 'type': 'atom', 'class': 'element', 'mw': 126.90447},
    {'name': 'XE', 'type': 'atom', 'class': 'element', 'mw': 131.29},
    {'name': 'CS', 'type': 'atom', 'class': 'element', 'mw': 132.91},
    {'name': 'BA', 'type': 'atom', 'class': 'element', 'mw': 137.33},
    {'name': 'PR', 'type': 'atom', 'class': 'element', 'mw': 140.91},
    {'name': 'EU', 'type': 'atom', 'class': 'element', 'mw': 151.96},
    {'name': 'GD', 'type': 'atom', 'class': 'element', 'mw': 157.25},
    {'name': 'TB', 'type': 'atom', 'class': 'element', 'mw': 158.93},
    {'name': 'IR', 'type': 'atom', 'class': 'element', 'mw': 192.22},
    {'name': 'PT', 'type': 'atom', 'class': 'element', 'mw': 195.084},
    {'name': 'AU', 'type': 'atom', 'class': 'element', 'mw': 196.96657},
    {'name': 'HG', 'type': 'atom', 'class': 'element', 'mw': 200.59},
    {'name': 'PB', 'type': 'atom', 'class': 'element', 'mw': 207.2},
    {'name': 'U', 'type': 'atom', 'class': 'element', 'mw': 238.03},
]

# Dictionary of pKa values and unprotonated charge state.
PKA_DICT = {"ASP": 4.0,
            "CYS": 8.5,
            "GLU": 4.4,
            "TYR": 10.0,
            "CTERM": 3.1,
            "ARG": 12.0,
            "HIS": 6.5,
            "LYS": 10.4,
            "NTERM": 8.0}

CHARGE_DICT = {"ASP": -1.,
               "CYS": -1.,
               "GLU": -1.,
               "TYR": -1.,
               "CTERM": -1.,
               "ARG": 1.,
               "HIS": 1.,
               "LYS": 1.,
               "NTERM": 1.}

# Atom on which to place charge
TITR_ATOM = {"ASP": "CG ",
             "GLU": "CD ",
             "TYR": "OH ",
             "ARG": "CZ ",
             "HIS": "NE2",
             "LYS": "NZ "}

# Dictionary of van der Waal radii
VDW_DICT = {"N  ": 1.650,
            "CA ": 1.870,
            "C  ": 1.760,
            "O  ": 1.400,
            "AD1": 1.700,
            "AD2": 1.700,
            "AE1": 1.700,
            "AE2": 1.700,
            "CB ": 1.870,
            "CD ": 1.870,
            "CD1": 1.760,
            "CD2": 1.760,
            "CG ": 1.870,
            "CG1": 1.870,
            "CG2": 1.870,
            "CE ": 1.870,
            "CE1": 1.760,
            "CE2": 1.760,
            "CE3": 1.760,
            "CH2": 1.760,
            "CZ ": 1.870,
            "CZ2": 1.760,
            "CZ3": 1.760,
            "ND ": 1.650,
            "ND1": 1.650,
            "ND2": 1.650,
            "NE ": 1.650,
            "NE1": 1.650,
            "NE2": 1.650,
            "NH1": 1.650,
            "NH2": 1.650,
            "NZ ": 1.650,
            "OD ": 1.400,
            "OD1": 1.400,
            "OD2": 1.400,
            "OT2": 1.400,
            "OE ": 1.400,
            "OE1": 1.400,
            "OE2": 1.400,
            "OH2": 1.400,
            "OG ": 1.400,
            "OG1": 1.400,
            "OT1": 1.400,
            "OXT": 1.400,
            "OH ": 1.400,
            "SD ": 1.850,
            "SG ": 1.850,
            "P  ": 1.900}

METALS = ['LI', 'BE', 'NA', 'MG', 'K', 'CA', 'RB', 'SR', 'CS', 'BA', 'V', 'CR', 'MN', 'CO', 'NI', 'FE',
          'FE1', 'FE2', 'FE3', 'FE4', 'CO', 'NI', 'CU', 'ZN', 'Y', 'ZR1', 'ZR2', 'ZR3', 'MO', 'RU', 'RU1', 'RH',
          'RH1', 'PD', 'AG', 'CD', 'LA', 'HFA', 'HFB', 'HFC', 'HFD', 'HFE', 'TA1', 'TA2', 'TA3', 'TA4', 'TA5',
          'TA6', 'W', 'W1', 'RE', 'OS', 'IR', 'PT', 'PT1', 'AU', 'HG', 'CE', 'PR', 'SM', 'EU', 'GD', 'TB', 'HO',
          'ER', 'YB', 'LU', 'PA', 'U', 'AL', 'GA', 'GE', 'IN', 'SN1', 'SB', 'TL', 'PB']

# --------------------------------------------------------------------------- #
# Amino acid name data
# --------------------------------------------------------------------------- #

# List of three and one letter amino acid codes
_aa_index = [('ALA', 'A'),
             ('CYS', 'C'),
             ('ASP', 'D'),
             ('GLU', 'E'),
             ('PHE', 'F'),
             ('GLY', 'G'),
             ('HIS', 'H'),
             ('HSE', 'H'),
             ('HSD', 'H'),
             ('ILE', 'I'),
             ('LYS', 'K'),
             ('LEU', 'L'),
             ('MET', 'M'),
             ('MSE', 'M'),
             ('ASN', 'N'),
             ('PRO', 'P'),
             ('GLN', 'Q'),
             ('ARG', 'R'),
             ('SER', 'S'),
             ('THR', 'T'),
             ('VAL', 'V'),
             ('TRP', 'W'),
             ('TYR', 'Y')]
