#!/usr/bin/env bash
echo ''
echo 'Copyright (c) 2017 LIEStudio, VU Amsterdam'
echo 'In collaboration with Zefiros Software, www.zefiros.eu.'
echo ''
echo '================ Welcome to the Docker image for LIEStudio ================'
echo 'This container comes with some commands to make your work less complicated!'
echo ''
echo 'Usage:'
echo '    helpme          Show this'
echo '    livedocs        Compile and serve the documentation (on port 8000)'
echo '    docs            Compile the documentation'
echo '    serve           Start the web-server, watch for changes'
echo '    compile         Compile the web resources'
echo '    root            Switch to root user'
echo '    lieuser         Switch to lieuser (if running in user-mode)'
echo '    lietest         Runs the python unit tests'
echo '    liecov          Runs the python unit tests with coverage reporting'
echo ''
echo ''